"""create_dead_letter_tasks_table

Revision ID: 62c89beff679
Revises: d2dabde1475b
Create Date: 2026-09-03 15:46:50.147435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '62c89beff679'
down_revision: Union[str, Sequence[str], None] = 'd2dabde1475b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dead_letter_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('input_data', sqlite.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('requeued_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dead_letter_tasks_job_id'), 'dead_letter_tasks', ['job_id'], unique=False)
    op.create_index(op.f('ix_dead_letter_tasks_task_id'), 'dead_letter_tasks', ['task_id'], unique=False)
    op.create_index(op.f('ix_dead_letter_tasks_workflow_id'), 'dead_letter_tasks', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dead_letter_tasks_workflow_id'), table_name='dead_letter_tasks')
    op.drop_index(op.f('ix_dead_letter_tasks_task_id'), table_name='dead_letter_tasks')
    op.drop_index(op.f('ix_dead_letter_tasks_job_id'), table_name='dead_letter_tasks')
    op.drop_table('dead_letter_tasks')
    # ### end Alembic commands ###
